-- Create the equipment_lease table for Kerala Panchayats
CREATE TABLE equipment_lease (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    price_per_day NUMERIC NOT NULL,
    owner_name TEXT NOT NULL,
    panchayat_location TEXT NOT NULL,
    contact_number TEXT NOT NULL,
    is_available BOOLEAN DEFAULT TRUE,
    image_url TEXT
);

-- ═══════════════════════════════════════════════════════════════
-- Row Level Security (RLS)
-- Security posture:
--   READ  → public (anon) — equipment listings are public information
--   WRITE → authenticated users only — prevents anonymous data tampering
-- ═══════════════════════════════════════════════════════════════

-- Enable Row Level Security (RLS)
ALTER TABLE equipment_lease ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can read equipment listings
CREATE POLICY "Allow public read access"
ON equipment_lease
FOR SELECT
USING (true);

-- Policy: Only authenticated users can insert new equipment
CREATE POLICY "Allow authenticated insert"
ON equipment_lease
FOR INSERT
TO authenticated
WITH CHECK (true);

-- Policy: Only the row owner (matched by owner_name = user email) can update
-- NOTE: For production, add an owner_id UUID column referencing auth.users.id
--       and replace this with: USING (owner_id = auth.uid())
CREATE POLICY "Allow authenticated update"
ON equipment_lease
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- Policy: Only authenticated users can delete (tighten with owner_id in production)
CREATE POLICY "Allow authenticated delete"
ON equipment_lease
FOR DELETE
TO authenticated
USING (true);
