-- Create the equipment_lease table for Kerala Panchayats
CREATE TABLE equipment_lease (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    price_per_day NUMERIC NOT NULL,
    owner_name TEXT NOT NULL,
    panchayat_location TEXT NOT NULL,
    contact_number TEXT NOT NULL,
    is_available BOOLEAN DEFAULT TRUE,
    image_url TEXT
);

-- ═══════════════════════════════════════════════════════════════
-- Row Level Security (RLS)
-- Security posture:
--   READ  → public (anon) — equipment listings are public information
--   WRITE → authenticated users only — prevents anonymous data tampering
-- ═══════════════════════════════════════════════════════════════

-- Enable Row Level Security (RLS)
ALTER TABLE equipment_lease ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can read equipment listings
CREATE POLICY "Allow public read access"
ON equipment_lease
FOR SELECT
USING (true);

-- Policy: Only authenticated users can insert new equipment
CREATE POLICY "Allow authenticated insert"
ON equipment_lease
FOR INSERT
TO authenticated
WITH CHECK (true);

-- Policy: Only the row owner (matched by owner_name = user email) can update
-- NOTE: For production, add an owner_id UUID column referencing auth.users.id
--       and replace this with: USING (owner_id = auth.uid())
CREATE POLICY "Allow authenticated update"
ON equipment_lease
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- Policy: Only authenticated users can delete (tighten with owner_id in production)
CREATE POLICY "Allow authenticated delete"
ON equipment_lease
FOR DELETE
TO authenticated
USING (true);

-- ═══════════════════════════════════════════════════════════════
-- Performance Indexes
-- ═══════════════════════════════════════════════════════════════

-- Speed up category filter queries (used in LeasingEconomy.jsx .eq('category', ...))
CREATE INDEX idx_equipment_lease_category
  ON equipment_lease (category);

-- Partial index for availability filter — only indexes available rows, smaller & faster
CREATE INDEX idx_equipment_lease_available
  ON equipment_lease (is_available)
  WHERE is_available = TRUE;

-- Speed up the default sort (most recent first)
CREATE INDEX idx_equipment_lease_created_at
  ON equipment_lease (created_at DESC);

-- Composite index for the common search pattern: category + availability
CREATE INDEX idx_equipment_lease_category_available
  ON equipment_lease (category, is_available);

-- ═══════════════════════════════════════════════════════════════
-- Supabase Storage — equipment-images bucket
-- ═══════════════════════════════════════════════════════════════
-- Storage buckets cannot be created via SQL. Follow these steps
-- in the Supabase Dashboard → Storage:
--
--   1. Create a new bucket named: equipment-images
--   2. Set "Public bucket" = ON (so image URLs work without auth tokens)
--   3. Add a policy: allow authenticated users to INSERT (upload)
--   4. Optional: set file size limit to 3MB in bucket settings
--
-- The AddEquipmentModal compresses images to ≤800×600 before upload,
-- so the effective size is typically 100–300 KB.

-- ═══════════════════════════════════════════════════════════════
-- Production Hardening — owner_id column (future migration)
-- ═══════════════════════════════════════════════════════════════
-- When authentication is fully implemented, run this migration:
--
-- ALTER TABLE equipment_lease
--   ADD COLUMN owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
--
-- Then replace the UPDATE/DELETE policies above with:
--
-- CREATE POLICY "Owner can update own equipment"
-- ON equipment_lease FOR UPDATE TO authenticated
-- USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());
--
-- CREATE POLICY "Owner can delete own equipment"
-- ON equipment_lease FOR DELETE TO authenticated
-- USING (owner_id = auth.uid());

