-- Create the equipment_lease table for Kerala Panchayats
CREATE TABLE equipment_lease (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    price_per_day NUMERIC NOT NULL,
    owner_name TEXT NOT NULL,
    panchayat_location TEXT NOT NULL,
    contact_number TEXT NOT NULL,
    is_available BOOLEAN DEFAULT TRUE,
    image_url TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE equipment_lease ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access (for hackathon demo)
CREATE POLICY "Allow public read access" 
ON equipment_lease 
FOR SELECT 
USING (true);
